import type { Metadata } from 'next';
import './globals.css';
import QueryProvider from '@/lib/reactQuery';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <QueryProvider>
        <body>{children}</body>
      </QueryProvider>
    </html>
  );
}
